version: '3'
services:
  app:
    container_name: "micro-app"
    build: "./docker"
    volumes:
      - "${SRC}:${GO_PROJECT_DIR}"
    ports:
      - "8080:8080"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/app"

  another-app:
    container_name: "micro-app-1"
    build: "./docker"
    volumes:
      - "${SRC}:${GO_PROJECT_DIR}"
    ports:
      - "8181:8181"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/wiki"
