version: "3"
services:
  app:
    container_name: go-dev
    build:
      context: ./docker
      args:
        projectDir: ${GO_PROJECT_DIR}
    volumes:
      - ${SRC}:${GO_PROJECT_DIR}
    ports:
      - "8080:8080"
