settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: wiki
  path: .
  commands:
    fmt:
      status: true
      args:
      - -s
      - -w
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
